language: java
sudo: false

jdk:
  - oraclejdk7

git:
  submodules: false

install: true
script: ./travis.sh
env:
  - TEST=CI
  - TEST=plugin
    SQ_VERSION=LTS
matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env: TEST=ruling PROJECT=fluent_http SQ_VERSION=LATEST_RELEASE
    - jdk: oraclejdk8
      env: TEST=ruling PROJECT=apache_commons_beanutils SQ_VERSION=LATEST_RELEASE
    - jdk: oraclejdk8
      env: TEST=ruling PROJECT=guava SQ_VERSION=LATEST_RELEASE
    - jdk: oraclejdk8
      env: TEST=ruling PROJECT=java_squid SQ_VERSION=LATEST_RELEASE
    - jdk: oraclejdk8
      env: TEST=ruling PROJECT=sonarqube_server SQ_VERSION=LATEST_RELEASE
    - jdk: oraclejdk8
      env: TEST=ruling PROJECT=jboss_ejb3_tutorial SQ_VERSION=LATEST_RELEASE

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
   # URL to QA hook, including credentials
      - secure: "jioMmc06IBRAgbWiyUP8T0ZsWPn+QhAf/UoGocYo5la20RMMb0M5A5Lpl7yvyGFv+PmC2SIlG3FHf61nRvHNaq1zSWGwOgmGZUrhz/tCD3caSB+BJoba46pcYL/W/V7X2nXMzhJiCbU3U4JoGwVUYqt3Ug1Jl/oLBk2IUp2U0zg="
